### PR TITLE
Parse requests and limits for Persistent Volume Claim

### PR DESCRIPTION
**Pull request by zakiva**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1508372

Depends on: 
https://github.com/ManageIQ/manageiq-schema/pull/74 - Merged
https://github.com/ManageIQ/manageiq/pull/16026 - Merged

@miq-bot add_label enhancement

@simon3z @zeari Please review

### CODE REVIEW

**Comment by moolitayer** [comment]
re kicking Travis

**Comment by moolitayer** [comment]
@zakiva is this targeted for Gaprindashvili? if so we will need a label and a bug

**Comment by zakiva** [comment]
> @zakiva is this targeted for Gaprindashvili? if so we will need a label and a bug

Yes, I opened a BZ and added it in the description above.

**Comment by zakiva** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by moolitayer** [comment]
Kicking Travis

**Comment by moolitayer** [comment]
I'm Removing the Gaprindashvili tag. The Schema PR ins't in Gaprindashvili and I see no Ticket targeted for it.
@miq-bot remove_label gaprindashvili/yes
@miq-bot add_label gaprindashvili/no

**Comment by moolitayer** [comment]
My Mistake, ManageIQ/manageiq-schema#74 is in G.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 2fc6bf604b1afc439f32c2728dc2b063bf7787a7
Author: Mooli Tayer <mtayer@redhat.com>
Date:   Wed Nov 15 12:16:32 2017 +0200

    Merge pull request #116 from zakiva/claim_requests_and_limits
    
    Parse requests and limits for Persistent Volume Claim
    (cherry picked from commit e3a711af542f8ba68373e3cd5e2e17198c1b3f51)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1513482
```

**Pull request merged**
