### PR TITLE
Bump to ruby 2.4.4 for great justice

### PR DESCRIPTION
**Pull request by jrafanie**
Bump to ruby 2.4.4 for great justice

### CODE REVIEW

**Comment by cben** [comment]
@jrafanie Travis failed (same in https://github.com/ManageIQ/manageiq-providers-openshift/pull/97 too)

**Comment by jrafanie** [comment]
Closing for now, the failure is caused by ruby 2.4.4 and has been documented, but not adequately fixed, in bundler/bundler#6340 and travis-ci/travis-ci#9333. The workaround of gem install bundler in before_install conflicts with how we run bin/setup in the install phase since we do that here. Note, ruby 2.4.3 works so maybe we'll go with that for now.

**Comment by cben** [comment]
Reopening to test whether Travis indeed fixed this https://github.com/travis-ci/travis-ci/issues/8969#issuecomment-390330259

**Comment by jrafanie** [comment]
> Reopening to test whether Travis indeed fixed this travis-ci/travis-ci#8969 (comment)

Thanks @cben.  I reopened the main repo's PR and will see what happens.  If good, I can reopen all of my PRs for review/merge in the next sprint.

**Comment by jrafanie** [comment]
This is now ready to go 🙇 @cben

**Comment by cben** [comment]
@moolitayer Skipping our usual 2-reviewers rule as there is nothing to really review, it's identical to core https://github.com/ManageIQ/manageiq/pull/17433 and [similar PRs in all repos](https://github.com/travis-ci/travis-ci/issues/9333#ref-pullrequest-324098751) that got enough eyes...

But I'm recently sliding towards "I simply merge stuff when I feel like" :-), let's talk whether that's OK...

**Pull request merged**
