### PR TITLE
Refactor parse_container_image

### PR DESCRIPTION
**Pull request by cben**
Created helpers for the pattern of looking in `@data_index`, if not there adding to `@data` and `@data_index`.
Repays some of the tech debt from #11.

I also have upcoming use for `find_or_store_data` — to keep track of all mapped tags, allowing some batching (faster and needed for tag mapping in graph refresh).

@miq-bot add-label refactoring

### CODE REVIEW

**Comment by cben** [comment]
@yaacov @zakiva @moolitayer please review

**Comment by agrare** [comment]
@simon3z can you assign a milestone for this PR?

**Comment by simon3z** [comment]
> @simon3z can you assign a milestone for this PR?

@agrare at the second one I already feel that it should be an automated bot task :rofl:

**Comment by agrare** [comment]
@simon3z haha I stopped after 2, if it were a bot you'd have at least 4 :)

**Pull request merged**
