### PR TITLE
Use k8s provider in k8s tests

### PR DESCRIPTION
**Pull request by moolitayer**
Should fix test failures of https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/38

### CODE REVIEW

**Comment by moolitayer** [comment]
@miq-bot add_label tests

@yaacov please review

**Comment by moolitayer** [comment]
@cben please review

**Comment by cben** [comment]
Yay solves half of #34.
AFAICT we don't have a matching test with ems_openshift in openshift repo.  Would it be worth having?

**Comment by moolitayer** [comment]
@cben AFAIK it tests code that is in this repo.
I think we are better off this way - 
we might change that code together with the tests, and then the openshift repo will start failing.

**Comment by moolitayer** [comment]
> It's definitely better this way, I'm only asking if we also want to test this code against openshift EMS in case the behavior differs.

Yeah that's what I was referring to above. Anyway I don't have a strong opinion on that, if you feel we are better off duplicating the tests to manageiq-providers-openshift as well go ahead.

**Pull request merged**
