### PR TITLE
Provide backward compatible way to globally set permitted classes

### PR DESCRIPTION
**Pull request by jrafanie**
This supports rails 7 and 6.1.

Similar to the change in: https://github.com/ManageIQ/manageiq/pull/22887

### CODE REVIEW

**Comment by Fryguy** [comment]
Minor, but can we
1. move this into a spec/support file in core
2. use that shared spec/support method here
3. Put a note in the spec/support entry that somehow let's us find it later (maybe a comment about the Rails version or something that we can search on).

My main concerns are duplication of code and then being able to find all those later when we need to undo it.

**Comment by Fryguy** [comment]
Actually i said spec/support but the original code is in yaml_permitted_classes, so maybe it's just easy to refactor into another method on that module and use it here.  Just trying to avoid the duplication.

**Comment by jrafanie** [comment]
> Minor, but can we
> 
> 1. move this into a spec/support file in core
> 2. use that shared spec/support method here
> 3. Put a note in the spec/support entry that somehow let's us find it later (maybe a comment about the Rails version or something that we can search on).
> 
> My main concerns are duplication of code and then being able to find all those later when we need to undo it.

Sure, I'll add a follow up item to the rails 7 todo list to find a generic way for all of the various repos to do the same function.  Or maybe just delete the rails 6.1 way when it's dropped.  Currently debugging tough api and ui-classic test failures so cleanup is less priority.

**Comment by jrafanie** [comment]
ok, I added a followup item to https://github.com/ManageIQ/manageiq/issues/22052

**Comment by jrafanie** [comment]
@Fryguy this is ready to go.  I'll come back and clean these up in the follow task: https://github.com/ManageIQ/manageiq/issues/22052.  When we drop rails 6.1, it should be easy to mass remove them.

**Review by Fryguy — APPROVED** [review]

**Pull request merged**
