### PR TITLE
Using EMS.destroy instead of EMS.orchestrate_destroy

### PR DESCRIPTION
**Pull request by jameswnl**
Depending on https://github.com/ManageIQ/manageiq/pull/16755

### CODE REVIEW

**Comment by jameswnl** [comment]
@miq-bot add_labels gaprindashvili/yes, bug, blocker

(Note the blocker bug is not in this repo)

**Comment by jameswnl** [comment]
@miq-bot remove_label wip

**Comment by jameswnl** [comment]
@zeari can you review this?

**Comment by cben** [comment]
LGTM.  I've not followed all details of https://github.com/ManageIQ/manageiq/pull/16755 but the simple fact is orchestrate_destroy is no more, there is only destroy now.

**Comment by jameswnl** [comment]
@cben thanks Beni

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit c99a5b16a80c8a60afb4926b1f2a82560c92a40b
Author: Adam Grare <agrare@redhat.com>
Date:   Wed Jan 17 17:06:41 2018 -0500

    Merge pull request #214 from jameswnl/destroy
    
    Using EMS.destroy instead of EMS.orchestrate_destroy
    (cherry picked from commit 281a8d857116b91690f930bf3b0944a28927f894)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1536039
    https://bugzilla.redhat.com/show_bug.cgi?id=1536041
```

**Pull request merged**
