### PR TITLE
bump image-inspector image version to 2.4

### PR DESCRIPTION
**Pull request by enoodle**
Use the new Image-Inspector image.

Main changelog for this version:
Enhancements:
* Can scan running containers
* Can use ClamAV Scanner
* Enable token authentication for web access
* Reports the status of image acquiring
* Support for authentication token to all endpoints

and many bugfixes.

Will solve a couple of BZs:

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1512824
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1484936

This will also allow us to move forward with another BZ https://bugzilla.redhat.com/show_bug.cgi?id=1524616 (which will also require a new version of image-inspector-client to be made..)

### CODE REVIEW

**Comment by enoodle** [comment]
cc @cben @moolitayer (for future reference) @zeari @nimrodshn

**Comment by cben** [comment]
Nice! Is there a changelog you can link to for the inspector?

**Comment by enoodle** [comment]
@cben I added at the top messsage

**Comment by cben** [comment]
Note Travis failure, spec expects `registry1/repository1:2.1`

**Comment by cben** [comment]
Sorry forgot this in "not sure if there's anything to review" mode.  Sounds great to me. @nimrodshn or @zeari you know this better now, please ack and I'll merge.

This can be bumped without new image-inspector-client, right?

**Comment by enoodle** [comment]
> This can be bumped without new image-inspector-client, right?

Yes, A new version of image-inspector-client is needed to use the endpoint authentication feature.

**Comment by cben** [comment]
Waiting for ack that 2.4 image is available on all channels.

**Comment by JPrause** [comment]
@cben if this can be backported, can you add the gaprindashvili/yes and fine/yes labels.

**Comment by cben** [comment]
^^ adding @zeari @nimrodshn who would know better if this is backportable

**Comment by nimrodshn** [comment]
checked with @cben:
`2.4` tag is not yet available on all channels:
```
$ skopeo inspect docker://docker.io/openshift/image-inspector
{
    "Name": "docker.io/openshift/image-inspector",
    "Digest": "sha256:a7f4f91655acf7190875d4968d2efb1218289a609f13994f8653648863c7d7c3",
    "RepoTags": [
        "2.0.0",
        "2.0",
        "2.1.0",
        "2.1.1",
        "2.1.2",
        "2.1",
        "2.2.0",
        "2.2",
        "2.3.0",
        "2.3",
        "2.4.0",
        "2.4",
        "latest",
        "v1.0.z",
        "v1.1.z",
        "v2.0.z",
        "v2.4.0"
    ],
...

$ skopeo inspect docker://registry.centos.org/openshift/image-inspector
{
    "Name": "registry.centos.org/openshift/image-inspector",
    "Digest": "sha256:50fb6f30ef7ab8b05591bc0dfc27a93881499bc90e823b8a7c6960757b47f0cc",
    "RepoTags": [
        "latest"
    ],
...

$ skopeo inspect docker://registry.access.redhat.com$ skopeo inspect docker://registry.centos.org/openshift/image-inspector
{
    "Name": "registry.centos.org/openshift/image-inspector",
    "Digest": "sha256:50fb6f30ef7ab8b05591bc0dfc27a93881499bc90e823b8a7c6960757b47f0cc",
/openshift3/image-inspector
{
    "Name": "registry.access.redhat.com/openshift3/image-inspector",
    "Digest": "sha256:036c51372fa6266ca631a445b6f8ff6cd6a674d1f859812190b065d7e573f581",
    "RepoTags": [
        "1.0.0",
        "1.0.0-11",
        "1.0.0-12",
        "v3.7.42-2",
        "2.1",
        "2.0",
        "v3.3",
        "v3.2",
        "v3.1",
        "v3.7",
        "v3.6",
        "v3.5",
        "v3.4",
        "v3.9",
        "v3.8",$ skopeo inspect docker://registry.centos.org/openshift/image-inspector
{
    "Name": "registry.centos.org/openshift/image-inspector",
    "Digest": "sha256:50fb6f30ef7ab8b05591bc0dfc27a93881499bc90e823b8a7c6960757b47f0cc",

        "v3.7.23-3",
        "v3.7.42",
        "2.1-19",
        "2.1-18",
        "2.1-16",
        "2.1-14",
        "v3.7.23",
        "2.1-12",
        "v3.8.36",
        "2.1-7",
        "2.1-6",
        "2.1-3",
        "2.1-9",
        "2.1-8",
        "2.0-2",
        "2.0-4",
        "v3.9.14",
        "v3.8.36-5",
        "1.0.0-8",
        "2.1-20",
        "v3.9.14-2",$ skopeo inspect docker://registry.centos.org/openshift/image-inspector
{
    "Name": "registry.centos.org/openshift/image-inspector",
    "Digest": "sha256:50fb6f30ef7ab8b05591bc0dfc27a93881499bc90e823b8a7c6960757b47f0cc",

        "1.0.0-5",
        "1.0.0-6",
        "latest"
    ],
...
```
that `latest` in CentOS registry is supposedly from a recent build of 2.4, but having `latest` without a specific version is useless...
anyway, manageiq/cloudforms out of the box only cares about:

- [x] `docker.io/openshift/image-inspector` (has 2.4)
- [ ] `registry.access.redhat.com/openshift3/image-inspector` (doesn't)

[This doesn't answer about future backportability]

**Comment by cben** [comment]
Ooh, 2.4 was released downstream!  `docker pull registry.access.redhat.com/openshift3/image-inspector:2.4` works.

Now will need to test it...

`$ skopeo inspect docker://registry.access.redhat.com/openshift3/image-inspector`
<details>
<pre>
{
    "Name": "registry.access.redhat.com/openshift3/image-inspector",
    "Digest": "sha256:5a711e0052a39597695c101325ec7c6ab3e61b960a1e6c3e2b31347e13477fdf",
    "RepoTags": [
        "v3.8",
        "1.0.0",
        "v3.9.27-1",
        "1.0.0-11",
        "1.0.0-12",
        "v3.7.44-3",
        "v3.7.46-1",
        "v3.9.25-1",
        "v3.7.42-2",
        "2.1",
        "2.0",
        "2.4",
        "v3.3",
        "v3.2",
        "v3.1",
        "v3.7",
        "v3.6",
        "v3.5",
        "v3.4",
        "v3.9.25",
        "v3.7.44",
        "v3.9.27",
        "v3.7.46",
        "v3.7.23-3",
        "v3.7.42",
        "2.1-19",
        "2.1-18",
        "2.1-16",
        "2.1-14",
        "v3.7.23",
        "2.1-12",
        "v3.8.36",
        "2.1-7",
        "2.1-6",
        "2.1-3",
        "2.1-9",
        "2.1-8",
        "2.0-2",
        "2.0-4",
        "v3.9.14",
        "v3.8.36-5",
        "1.0.0-8",
        "2.1-20",
        "v3.9.14-2",
        "1.0.0-5",
        "1.0.0-6",
        "v3.9",
        "latest"
    ],
    "Created": "2018-05-09T13:14:16.777883Z",
    "DockerVersion": "1.12.6",
    "Labels": {
        "License": "GPLv2+",
        "architecture": "x86_64",
        "authoritative-source-url": "registry.access.redhat.com",
        "build-date": "2018-05-09T13:13:24.036869",
        "com.redhat.build-host": "osbs-cpt-008.ocp.osbs.upshift.eng.rdu2.redhat.com",
        "com.redhat.component": "image-inspector-container",
        "description": "Image Inspector image for metrics collection.",
        "distribution-scope": "public",
        "io.k8s.description": "Image Inspector image for metrics collection.",
        "io.k8s.display-name": "Image Inspector",
        "io.openshift.tags": "openshift,inspector,image,security",
        "name": "openshift3/image-inspector",
        "release": "1",
        "summary": "Provides the latest release of Red Hat Enterprise Linux 7 in a fully featured and supported base image.",
        "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/image-inspector/images/v3.9.27-1",
        "vcs-ref": "2c01cd2607ec80410536b347066d4fefbecb57cf",
        "vcs-type": "git",
        "vendor": "Red Hat, Inc.",
        "version": "v3.9.27"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:d1fe25896eb5cbceebe612f6f820f433997d6748700d05f2029e8e077c02fd16",
        "sha256:001d79f6847029de668d289c5b602d004b2bf1691d29f31c643481e0821f03d2",
        "sha256:d736dc66f2d64b4dca6e74b6d3160bccc985ff93916cc4655d9270d245d715ae"
    ]
}
</pre></details>

**Comment by nimrodshn** [comment]
@cben  Wohho!

**Comment by cben** [comment]
Does this depend on new client (#236)?
openshift/image-inspector#38 added some new auth checking, and https://github.com/moolitayer/image-inspector-client/pull/17 starts sending the new header.
However Erez's PR description implies it's not directly dependent?

@nimrodshn @zeari What testing (if any) this needs before merging?

**Comment by cben** [comment]
Ah I see, #239 depends on new client #263, this I guess doesn't.

**Pull request closed without merging**
