### PR TITLE
Subclassed provider classes should mark the parent as a leaf class

### PR DESCRIPTION
**Pull request by Fryguy**
Depends on 
- [x] https://github.com/ManageIQ/manageiq-providers-amazon/pull/701
- [x] https://github.com/ManageIQ/manageiq-providers-openshift/pull/209

@agrare Please review.

### CODE REVIEW

**Comment by Fryguy** [comment]
@agrare We should cross-repo this but not sure how wide of a net to cast?

**Comment by agrare** [comment]
@miq-bot cross-repo-tests ManageIQ/manageiq-providers-amazon#701, ManageIQ/manageiq-providers-openshift#209, ManageIQ/manageiq-providers-kubernetes#433

**Review by agrare — APPROVED** [review]

**Comment by agrare** [comment]
@miq-bot cross-repo-tests ManageIQ/manageiq-providers-amazon#701, ManageIQ/manageiq-providers-openshift#209, ManageIQ/manageiq-providers-kubernetes#433, ManageIQ/manageiq, ManageIQ/manageiq-ui-classic, ManageIQ/manageiq-api

**Comment by agrare** [comment]
@Fryguy the three providers you changed plus core, api, and UI should cover it.  All look good to me will merge when https://travis-ci.com/github/ManageIQ/manageiq-cross_repo-tests/builds/224283338 is green

**Comment by Fryguy** [comment]
Ok I think I fixed in the openshift repo (containertemplate doesn't subclass there, but I coded it as if it did) - just rekicked the cross repo.

**Pull request merged**
