### PR TITLE
Bump kubeclient to 4.0

### PR DESCRIPTION
**Pull request by agrare**
Update to the latest version of kubeclient

### CODE REVIEW

**Comment by cben** [comment]
Yay.
@agrare I forgot to tell you I've released 4.1.0 including your chunking PR.

**Comment by agrare** [comment]
I saw thanks a lot @cben !

**Comment by simaishi** [comment]
Marking as `hammer/yes` as this goes with https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/125 which is `hammer/yes`.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit d68e5580d6d35695cce370fb3ab64ebf76cc2a8c
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Mon Dec 3 16:07:07 2018 -0500

    Merge pull request #311 from agrare/bump_kubeclient_4_0
    
    Bump kubeclient to 4.0
    
    (cherry picked from commit bbc66f03d091045515681ce63cb795276719063b)
```

**Pull request merged**
