### PR TITLE
[GAPRINDASHVILI] Final translations for gaprindashvili

### PR DESCRIPTION
**Pull request by mzazrivec**
This PR contains final translation fixes / polishing for Gaprindashvili GA

### CODE REVIEW

**Comment by cben** [comment]
@simaishi sorry, merged this to gaprindashvili without thinking that should check with you, and also forgot we're in blockers only :-|
@mzazrivec you say on https://github.com/ManageIQ/manageiq/pull/16860 it "should be merged with plugin PRs" — is there an order dependence?
@mzazrivec is there a BZ or are translations exempt from blocker requirements?

**Comment by mzazrivec** [comment]
@cben There's no order dependency. There's no bug that I know of, I just got an email from translators saying they polished / corrected some strings for the gaprindashvili release, so here they are.

**Comment by moolitayer** [comment]
:+1:

**Comment by moolitayer** [comment]
Feels like this should have been a master + backport fix (why not have this fix on master as well)

**Comment by mzazrivec** [comment]
In general, master catalogs differ from whatever is in gaprindashvili, so a plain cherry pick / backport wouldn't work. And even if the backport would work, there's still a big chance that the backported catalogs won't be complete.

**Pull request merged**
