### PR TITLE
[GAPRINDASHVILI] Update i18n catalogs for gaprindashvili release

### PR DESCRIPTION
**Pull request by mzazrivec**

### CODE REVIEW

**Comment by moolitayer** [comment]
@mzazrivec can you give some context on what these come from (some automated process?) and why we are adding them in Gaprindshvili (and not master first)

**Comment by mzazrivec** [comment]
Creation of gettext catalogs is documented in manageiq docs. We're adding them in gaprindashvili
branch, since that's what we're doing the translations for. Not for master.

**Comment by moolitayer** [comment]
Sorry i'm new to this, can you provide a link please?
(Why are the strings empty?)

**Comment by cben** [comment]
https://github.com/ManageIQ/guides/blob/master/i18n.md perhaps?

**Pull request merged**
