### PR TITLE
Do not run vcr 3 times

### PR DESCRIPTION
**Pull request by yaacov**
**Description**

Because of rspec context switching `@node` is always `nil` in line 28.

To make the `@targets` _reference_ global it need to be defined in a `:all` context.

Here we declare the `@targets` in the `:all` context, and the check for `@target.empty?` will check the global context as expected 🎆 .

### CODE REVIEW

**Comment by yaacov** [comment]
While checking a similar issue in @cben 's PR, we found that here we poll the vcr 3 times, the `@node == nil` was done with new context each time, and was always nil.

@simon3z @moolitayer @cben please review.

p.s.
PR #159 will touch the same file ... so this or #159 will have to be rebased after the other is merged ..

**Comment by yaacov** [comment]
Ahhh, checking with @cben, we must put the `@ems = FactoryGirl.create` in the `:all` context for this to work, o/w `@ems` will not be saved between `context` switching and may or may not be available for the tests ...

closing in favour of #135

**Comment by moolitayer** [comment]
can we put the initialization block `before(:all)`?

**Comment by cben** [comment]
yes, see #185

**Pull request closed without merging**
