### PR TITLE
Fail on creating scanning job with image instance

### PR DESCRIPTION
**Pull request by zakiva**
Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/105. 

This PR removes the backward compatibility kept in https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/105. In case of creating a scanning job with image instance (instead of class) an explicit exception will be raised.

### CODE REVIEW

**Comment by zakiva** [comment]
@simon3z @moolitayer @cben

**Comment by zakiva** [comment]
@miq-bot add_label fine/no

**Comment by simon3z** [comment]
@zakiva @moolitayer where are the `message-buffer` travis failure coming from?

**Comment by zakiva** [comment]
@simon3z I don't think it's related to this PR, it fails on master too.

**Comment by zakiva** [comment]
@simon3z I don't know but I think it was introduced in https://github.com/ManageIQ/manageiq/pull/16024. 
cc @jrafanie

**Comment by jrafanie** [comment]
> @simon3z I don't know why exactly, but I think it was introduced in ManageIQ/manageiq#16024.
> Should we just require 'application_helper' in this repo?
> cc @jrafanie

@zakiva If you need application_helper in this repo, please require it here.  We want to detangle 🍝  dependencies in the main repo so we can't put it back there.

**Comment by jrafanie** [comment]
@zakiva in the main repo, you can now run `BUNDLER_GROUPS=manageiq_default bundle exec rspec path/to/spec` and it won't include the manageiq-classic-ui code and won't parse the enormous routes file... same with rails console.  The idea is we want to break apart dependencies even further so we need to specify dependencies correctly at the places we use them.

**Pull request merged**
