### PR TITLE
Delete Prometheus Alerts MonitoringManager

### PR DESCRIPTION
**Pull request by agrare**
This was only supported on OCPv3 and is not expected to be reimplemented in the future.

Based on: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/506

NOTE I split this out from https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/506 because we might want to backport that (it causes user confusion) where as this is strictly a backend cleanup that also will require some data migrations to delete any old records.

### CODE REVIEW

**Comment by kbrock** [comment]
kicking

**Comment by kbrock** [comment]
ok, looks like the test failure is trivial but legit. The list has changed:

```
       the missing elements were: [
         "manageiq-providers-openshift_monitoring_manager_event_catcher.target",
         "manageiq-providers-openshift_monitoring_manager_event_catcher@.service"
       ]
     # ./spec/manageiq/spec/models/miq_worker/systemd_common_spec.rb:19:in `block (3 levels) in <top (required)>'
```

Confused why this is showing up here though.
Maybe a rebase would fix?

**Comment by agrare** [comment]
The test is correct I forgot to remove the systemd unit files for the deleted worker classes

**Comment by agrare** [comment]
Closing in favor of https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/518

**Pull request closed without merging**
