### PR TITLE
[GAPRINDASHVILI] [Changelog] Update for Gaprindashvili Beta1

### PR DESCRIPTION
**Pull request by JPrause**

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by moolitayer** [comment]
@JPrause could you please start all the commit messages with `Changelog: X` (e.g `Changelog: Update for Gaprindashvili Beta1`) from this point on? I'm asking since we often look at logs, and it would help if these commits were easily distinguishable.

Also please squash the two commits to one.

**Comment by JPrause** [comment]
That's a fantastic idea. I'll be doing that for all the repos.

**Comment by moolitayer** [comment]
@JPrause what I actually meant was the git commit messages (we look quite often at `git log`)  to have a prefix. Also please going forward let's have one commit per change (e.g 	
squash `Add further backports` commit onto `Update changelog for GBeta1 backport` which is what is more interesting to a log reader). Other then that this work on the changelog is great! please contact me if you have any questions, thanks!

**Pull request merged**
