### PR TITLE
We need to use existing relation to project so we build valid query

### PR DESCRIPTION
**Pull request by Ladas**
Depends on:

- [x] https://github.com/ManageIQ/manageiq/pull/16741

We need to use existing relation to project so we build valid query,
otherwise the targeted specs fails.

### CODE REVIEW

**Comment by Ladas** [comment]
@cben the core dependency brings local db index loaders for secondary indexes. But that fails the current targeted refresh spec, because we are using blacklisted 'namespace'. I will add more validations so the Graph refresh shouts when we add invalid combination of columns for the index.

**Comment by cben** [comment]
Great!  We need to move in this direction.
Are you planning to convert all `:by_namespace_and_name` usages?

I think when done we can stop passing :namespace to inv collections (and blacklisting it):
```diff
h[:container_project] = lazy_find_project(:name => h[:namespace])
h[:container_project] = lazy_find_project(:name => h.delete(:namespace))
```

**Comment by Ladas** [comment]
@cben yes will do, I will first write asserts, that will tell me what to do :-D

**Comment by Ladas** [comment]
@cben ok, these are all occurrences that the new asserts in core shows, sending also OpenShift PR. Could you then remove the actual namespace as followup? I don't want to mess that up. :-)

**Comment by cben** [comment]
@miq-bot add-label gaprindashvili/no
(going over unlabeled PRs...  assuming no as this depends on several unbackported enhancement core PRs with like 40 commits.)

**Pull request merged**
