### PR TITLE
Remove ContainerTemplateMixin from Kubernetes

### PR DESCRIPTION
**Pull request by agrare**
The ContainerTemplate operations are openshift specific and shouldn't be in the kubernetes repo

Original issue: https://github.com/ManageIQ/manageiq/pull/15523
Depends on: https://github.com/ManageIQ/manageiq-providers-openshift/pull/165

### CODE REVIEW

**Comment by agrare** [comment]
@cben does this even belong in the kubernetes repo?  I don't see us collecting any ContainerTemplates in the kubernetes refresh parser and it appears that this is an openshift specific type.

**Comment by chessbyte** [comment]
[Test failure](https://travis-ci.com/github/ManageIQ/manageiq-providers-kubernetes/jobs/317099446) looks legit

**Comment by agrare** [comment]
@chessbyte that failure is because the `Openshift::ContainerManager::ContainerTemplate` on master still includes the ContainerTemplateMixin.  This will go green after https://github.com/ManageIQ/manageiq-providers-openshift/pull/165 is merged.  I've marked this as dependent on that PR

**Comment by chessbyte** [comment]
@agrare Would you please make a cross-repo PR to verify your assumption

**Comment by agrare** [comment]
@chessbyte :+1: https://travis-ci.com/github/ManageIQ/manageiq-cross_repo-tests/builds/159418530 green

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit e8c71ac8b4e21428e69a83195b7ad3846d4c5f5f
Author: Oleg Barenboim <chessbyte@gmail.com>
Date:   Wed Apr 8 14:38:55 2020 -0400

    Merge pull request #365 from agrare/pass_api_group_to_connect

    Remove ContainerTemplateMixin from Kubernetes

    (cherry picked from commit 3ffdfcf12c4105feb375124f9c61f032b0857552)
```

**Pull request merged**
