### PR TITLE
[WIP] Abstract the metric capture code

### PR DESCRIPTION
**Pull request by yaacov**
**Description**

Current metrics capture code is Hawkular centric, this PR abstracts metrics capture.
Now we have an abstracted `CaptureContextMixin` module, and a data store specific `<DataStore>CaptureContext` classes the implement specific data-store code.

### CODE REVIEW

**Comment by yaacov** [comment]
@miq-bot add_label compute/containers, refactoring

@simon3z @cben @moolitayer @zeari please review

**Comment by yaacov** [comment]
@zakiva please review

**Comment by zakiva** [comment]
looks good overall :+1: 
Is there a way to avoid using `allow_any_instance_of`? 
cc @moolitayer

**Comment by yaacov** [comment]
> Is there a way to avoid using allow_any_instance_of?

@zakiva , 👍 looking into it, will fix that in a new PR

**Comment by yaacov** [comment]
@miq-bot add_label wip

@moolitayer @simon3z this will wait until the PR about using new metrics endpoints is merged

**Comment by simon3z** [comment]
@yaacov as mentioned today, let's try if we can move to the new metrics before the refactoring (it could be easier/nicer for the backports)

**Comment by yaacov** [comment]
Unmergebale, 

This is a ~"two liner" I wrote to make it easier to implement https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/47 and https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/20, since https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/47 will be done without it, closing for now.

**Comment by moolitayer** [comment]
> @yaacov as mentioned today, let's try if we can move to the new metrics before the refactoring (it could be easier/nicer for the backports)

@simon3z I don't understand, are we planning to backport prometheus related PRs?

**Comment by simon3z** [comment]
> @simon3z I don't understand, are we planning to backport prometheus related PRs?

@moolitayer "new metrics" for @yaacov means "better hawkular metrics series" :blush:

**Comment by moolitayer** [comment]
oh ok @simon3z thanks

**Pull request closed without merging**
