### PR TITLE
Move kubernetes code from gems-pending

### PR DESCRIPTION
**Pull request by nimrodshn**
Move kubernetes code from gems pending to relevant repo.
Issue #19 
Miq gems PR:https://github.com/ManageIQ/manageiq-gems-pending/pull/185
cc: @cben @simon3z @chessbyte

### CODE REVIEW

**Comment by nimrodshn** [comment]
@simon3z me and @cben werent sure about where to put this file inside `manageiq-providers-kubernetes`. Thoughts?

**Comment by moolitayer** [comment]
Are there tests that need to move too @nimrodshn

**Comment by nimrodshn** [comment]
@moolitayer nope.

**Comment by moolitayer** [comment]
I don't think belongs under lib in this repository.
I think this belongs in our usual namespace and should sit with other event collection classes

**Comment by nimrodshn** [comment]
@moolitayer ofcourse.
@cben and I thought we should first move it under `/lib` - corresponding to the original path, and then move it to `app/models` etc in a different PR thus making it easier to follow the history of the repo split.
If you think it's better to do it at once I'll do it. @cben Thoughts?

**Comment by moolitayer** [comment]
If we are moving this into this repo I prefer to move it into our namespace and in the same PR switch the collection code to look at that namespace. Lets start by investigating how other providers handled this issue

**Comment by nimrodshn** [comment]
@moolitayer here's what they did in manageiq-providers-ovirt: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/9

**Comment by moolitayer** [comment]
ok thanks @nimrodshn I've looked at https://github.com/ManageIQ/manageiq-providers-ovirt/pull/9/files#r111120109 I'm still in favor of moving into moving to our namespace.

Deferring namespace question to @simon3z

Of curse we will need to carefully test this anyway (Run all the tests in manageiq/manageiq on top of this PR and ManageIQ/manageiq-gems-pending#185 to make sure we don't break manageiq master like these changes often do)

**Comment by simon3z** [comment]
> ok thanks @nimrodshn I've looked at https://github.com/ManageIQ/manageiq-providers-ovirt/pull/9/files#r111120109 I'm still in favor of moving into moving to our namespace.
> 
> Deferring namespace question to @simon3z

@moolitayer @nimrodshn in oVirt it seems that they moved itto their namespace, isn't it? (`OvirtEventMonitor` => `ManageIQ::Providers::Ovirt::Legacy::EventMonitor`).
I am in favor of that.

**Comment by moolitayer** [comment]
> @moolitayer @nimrodshn in oVirt it seems that they moved itto their namespace, isn't it? (OvirtEventMonitor => ManageIQ::Providers::Ovirt::Legacy::EventMonitor).
> I am in favor of that.

:+1: for the class namespace we need to do adapt.

 I was looking at the the fact that they put the class under `lib/` directory. According to the discussion [there](https://github.com/ManageIQ/manageiq-providers-ovirt/pull/9/files#r111119033) we should not have the same problem and should be able to move the class under our regular directory structure as well.

@nimrodshn Let me know if there is any problem with:
- Moving the class to our namespace
- Moving the file under a directory to fit that namespace

Thanks

**Comment by nimrodshn** [comment]
@moolitayer PTAL .

**Comment by moolitayer** [comment]
@nimrodshn Looks good, lets see if you can move the global variable ignores from the main repo as discussed

**Comment by nimrodshn** [comment]
@moolitayer PTAL again :)

**Comment by moolitayer** [comment]
@nimrodshn did you get a chance to test events collection on top of this and the ManageIQ pr?

**Comment by nimrodshn** [comment]
@moolitayer nope :crying_cat_face: 
Show me how to do this over PM?

**Comment by moolitayer** [comment]
> @moolitayer nope 
> Show me how to do this over PM, plz.

Sure come find me when you have some free time.

**Comment by chessbyte** [comment]
@nimrodshn @moolitayer bump

**Comment by moolitayer** [comment]
Waiting for @nimrodshn to test this

**Comment by nimrodshn** [comment]
Tested this along side the manageiq-gems-pending PR and works fine ! :+1: 
@moolitayer  @chessbyte

**Comment by nimrodshn** [comment]
Hooray! :tada:

**Pull request merged**
