### PR TITLE
Use k8s provider in k8s tests

### PR DESCRIPTION
**Pull request by moolitayer**
- Use k8s provider in k8s tests
- Remove lots of VCR interactions not actually needed in the test (but called by an OpenShift refresh)

### CODE REVIEW

**Comment by moolitayer** [comment]
@cben @yaacov please review

**Comment by moolitayer** [comment]
@cben please review

**Comment by bdunne** [comment]
@moolitayer Any reason there's no milestone here?

**Comment by moolitayer** [comment]
@bdunne I see we haven't been using these consistently here. couple of questions:
- are they used only for searches or do they have another meaning? 
- Is there any kind of automation or is it all manual?
- Is it according to the build calendar (in case we need to fix old PRs)

Thanks

cc @simon3z

**Comment by bdunne** [comment]
- Some people have complaints about the statistics slide in the sprint review.  It currently shows all closed PR's during the sprint.  In a few repos, navigating to the closed PR's page and filtering by milestone will give you different numbers than the script that generates the statistics slide.  This is because:
  - We don't assign a milestone to closed but not merged PR's
  - Some merged PR's don't have a milestone assigned
- There is an open issue for the bot to request that a milestone (and certain flags) be set on a PR.
- The milestone is based on the PR merge time.

**Comment by cben** [comment]
Why not have the bot just set the milestone based on merge time?

**Comment by moolitayer** [comment]
https://github.com/ManageIQ/miq_bot/issues/27

**Pull request merged**
